# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mysql-pvc
#   namespace: php-wordpress
#   annotations:
#     volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:  
#     requests:
#       storage: 1Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: web-pvc
#   namespace: itheima-admin
#   annotations:
#     volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:  
#     requests:
#       storage: 1Gi