const version0 = '/app/v1_0/'
const version1 = '/app/v1_1/'
export const API_SENDCODE = `${version0}sms/codes/` // 获取短信验证码
export const API_LOGIN = `${version0}authorizations` // 用户登录
export const API_CHANNELS = `${version0}channels` // 全部新闻频道
export const API_USERCHANNELS = `${version0}user/channels` // 用户频道
export const API_ARTICLES = `${version1}articles` // 某频道下的文章
export const API_ARTICLE = `${version0}articles` // 文章详情
export const API_COMMENTS = `${version0}comments` // 获取评论或评论回复
export const API_FOLLOW = `${version0}user/followings` // 关注或取消关注用户
export const API_LIKEING = `${version0}article/likings` // 对文章点赞或者取消点赞接口
export const API_DISLIKING = `${version0}article/dislikes` // 对文章不喜欢或者取消不喜欢接口
export const API_COMMENTLIKE = `${version0}comment/likings` // 对评论或者评论回复点赞 或者取消点赞
export const API_USER = `${version0}user` // 拉取用户信息
export const API_USERS = `${version0}users` // 拉取其他用户信息
export const API_COLLECT = `${version0}article/collections` // 收藏接口
export const API_HISTORY = `${version0}user/histories` // 用户历史接口
export const API_USERPHOTO = `${version0}user/photo` // 编辑用户照片资料(头像,身份证照片)
export const API_USERPROFILE = `${version0}user/profile` // 用户资料
export const API_FOLLOWS = `${version0}user/followings` // 关注列表
export const API_FOLLOWERS = `${version0}/user/followers` // 粉丝列表
export const API_USERARTICLES = `${version0}/user/articles` // 当前用户列表
export const API_ANNOUNCEMENT = `${version0}announcements` // 系统公告
export const API_FIGURE = `${version0}user/figure` // 获取用户的统计数据
export const API_SEARCHHISTORY = `${version0}search/histories` // 搜索历史
export const API_SUGGESTION = `${version0}suggestion` // 搜索建议
export const API_SEARCH = `${version0}search` // 搜索结果
export const API_BLACKLIST = `${version0}user/blacklists` // 拉黑用户
export const API_REPORT_ARTICLE = `${version0}article/reports` // 举报文章
